### ISSUE TITLE
'kid' header is ignored

### ISSUE THREAD

**Issue by elijah-pl** [joolfe/postman-util-lib#25]
Defined header is not present in a generated token.

Passed headers to function:
```js
header = {
    'typ': 'JWT',
    'jku': 'https://localhost:8080/uaa/token_keys',
    'kid': 'key-id-1',
    'alg': 'RS256'
}
```

Decoded JWT:
```json
{"header": {"typ":"JWT","jku":"https://localhost:8080/uaa/token_keys","alg":"RS256"}, "payload": ...}
```

**Comment by elijah-pl** [comment]
Workaround: pass 'kid' as a part of JWK.

**Comment by joolfe** [comment]
Yes the kid is get from the JWK take into account that kid is part of [jwks](https://datatracker.ietf.org/doc/html/rfc7517) specification that's what is get from here.
