### ISSUE TITLE
feat: support JWK to validate JWT

### ISSUE THREAD

**Issue by theliuk** [joolfe/postman-util-lib#3]
At the moment, only a public key in `PEM` format is accepted to validate a `JWT`. 
It'd be very useful to support `JWK` too. This might be achieved by means of [this good library](https://github.com/Brightspace/node-jwk-to-pem).

**Comment by joolfe** [comment]
We should find a way to implement this with `jsrsasign` library because the need to be possible load in Postman, this means that should be browser compatible.

**Comment by theliuk** [comment]
I tried to browserify that library and it works. I already have it “installed” in my postman collection and working alongside to your library. 
I might propose an integration and submit a PR.

**Comment by joolfe** [comment]
`jsrsasign` already support this kind of operations, I have added support for both PEM or JWK in the `jwtVerify` method. please test

**Comment by theliuk** [comment]
I'll do
