### ISSUE TITLE
Unsupported public key alg: ecdsa

### ISSUE THREAD

**Issue by nurhazbiy** [joolfe/postman-util-lib#30]
Hello, i use this package to generate jwt token for app store connect, which need ecdsa. But when i tried to decrypt valid token for testing, it shows error on title, does this library does not support ECDSA? here is part of my code 
```
const result = pmlib.jwtVerify(token, jwtSecret,'ES256')
```

**Comment by joolfe** [comment]
Hi @nurhazbiy,

What is used under the hood is the [getKey](https://kjur.github.io/jsrsasign/api/symbols/KEYUTIL.html#.getKey) method from jrsasing, there is an issue here [172](https://github.com/kjur/jsrsasign/issues/172) that have your same problem, have a look but seems like the 'alg' value of the key is not correct/supported.

Best regards.
