### ISSUE TITLE
Request for AES-GCM Encryption Support

### ISSUE THREAD

**Issue by hfxu** [joolfe/postman-util-lib#35]
Hi Maintainers,

I'm writing to suggest an addition to your library - AES-GCM encryption support. The default CryptoJS library used by Postman lacks this feature, which is essential for secure data communication.

I believe adding AES-GCM support would significantly enhance your library's functionality and benefit many users.

Thank you for considering this request.

**Comment by joolfe** [comment]
Hi @hfxu,

This library was created as util for an old project in an old job but I´m not going to maintain it actively. I don´t archive this repo just to avoid "harm" people who can be actively using it but I will not add new features sorry.

If you want to create a PR with the feature I promise to review and try to merge but that's all.

Best regards
