### ISSUE TITLE
pmlib.rs.KJUR.crypto.Cipher.encrypt returns an empty error message.

### ISSUE THREAD

**Issue by LorincJuraj** [joolfe/postman-util-lib#8]
When signing string longer that 126 characters with 'RSAOAEP512' or 192 characters for RSAOAEP256 the script throws an error. There is no error text. This is the code I use:

```
eval(pm.globals.get('pmlib_code'))

const pubkey = '-----BEGIN CERTIFICATE-----\n' +
'...\n' +
'-----END CERTIFICATE-----\n';

var keyObj = pmlib.rs.KEYUTIL.getKey(pubkey);

let signingString = 'date: Tue, 18 Sep 2018 09:51:01 GMT\n' +
'digest: sha-512=z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==\n' +
'x-request-id: 95126d8f-ae9d-4ac3-ac9e-c357dcd78';

signingString = 'date: Tue, 18 Sep 2018 09:51:01 GMT\n' +
'digest: sha-512=z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==\n' +
'x-request-id: 11111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa';

let signature = pmlib.rs.KJUR.crypto.Cipher.encrypt(signingString, keyObj, 'RSAOAEP256');

console.log( 'signature:' );
console.log( signature );
```

But when I remove just a single character from the `signingString` I can see the proper output in the console.

**Comment by joolfe** [comment]
Hi @LorincJuraj,

"See PKCS#1 standrad. Data can be encrypted shall be smaller than its key." from kjur/jsrsasign#326, so you can use a bigger key or another type of key.

As a tip, the component `rs` is just an export of [jsrasign](https://github.com/kjur/jsrsasign) so if you have any error with that you can just look for the error in the jsrasign repo, for example for your problem I have create a test to reproduce and then look for the error on the repo and I have found this issues:

- https://github.com/kjur/jsrsasign/issues/326
- https://github.com/kjur/jsrsasign/issues/357
- https://stackoverflow.com/questions/15206594/rsa-message-too-long-javascript-jsbn

Best Regards.
